name: digital_wardrobe
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  email_validator: ^2.1.17
  cloud_firestore: ^5.6.9
  icons_flutter: ^0.0.5
  icons_plus: ^5.0.0
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.7

  cupertino_icons: ^1.0.8
  flutter_slidable: ^3.0.0
  share_plus: ^11.0.0
  auto_size_text: ^3.0.0
  flutter_material_color_picker: ^1.0.3
  flutter_colorpicker: ^1.0.3
  easy_localization: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/jacket.png
    - assets/icons/underwear.png
    - assets/icons/pants.png
    - assets/icons/hoodie.png

dependency_overrides:
  win32: ^5.14.0
