// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfb_xpwbEF6PSOG_0Fdn_A-U5sPkX2EAw',
    appId: '1:181900385303:web:9b0225da0bf942b8a3d052',
    messagingSenderId: '181900385303',
    projectId: 'digital-wardrobe-9468a',
    authDomain: 'digital-wardrobe-9468a.firebaseapp.com',
    storageBucket: 'digital-wardrobe-9468a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD09jTVQV9pD_Psoq6oC0BY5i1pzPn2Qfo',
    appId: '1:181900385303:android:68f41e4126dcf6ffa3d052',
    messagingSenderId: '181900385303',
    projectId: 'digital-wardrobe-9468a',
    storageBucket: 'digital-wardrobe-9468a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLoVuzjG998OLtpx5Z-mcY7x4NsFRz_q4',
    appId: '1:181900385303:ios:c4833c7be4d8c4e9a3d052',
    messagingSenderId: '181900385303',
    projectId: 'digital-wardrobe-9468a',
    storageBucket: 'digital-wardrobe-9468a.firebasestorage.app',
    iosBundleId: 'com.example.digitalWardrobe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLoVuzjG998OLtpx5Z-mcY7x4NsFRz_q4',
    appId: '1:181900385303:ios:c4833c7be4d8c4e9a3d052',
    messagingSenderId: '181900385303',
    projectId: 'digital-wardrobe-9468a',
    storageBucket: 'digital-wardrobe-9468a.firebasestorage.app',
    iosBundleId: 'com.example.digitalWardrobe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfb_xpwbEF6PSOG_0Fdn_A-U5sPkX2EAw',
    appId: '1:181900385303:web:66a31625968e3326a3d052',
    messagingSenderId: '181900385303',
    projectId: 'digital-wardrobe-9468a',
    authDomain: 'digital-wardrobe-9468a.firebaseapp.com',
    storageBucket: 'digital-wardrobe-9468a.firebasestorage.app',
  );

}